apiVersion: apps/v1
kind: Deployment
metadata:
  name: gyuweek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gyuweek
  template:
    metadata:
      labels:
        app: gyuweek
    spec:
      containers:
      - image: okteto.dev/gyuweek:latest
        name: gyuweek
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "f7cef36c-b734-4fe9-8ca6-46ac22b32359"
        - name: Vless_Path
          value: "/f7cef36c-b734-4fe9-8ca6-46ac22b32359"
        - name: Vmess_UUID
          value: "4dc98401-ada1-4bf6-8b83-c1357e9296fc"
        - name: Vmess_Path
          value: "/4dc98401-ada1-4bf6-8b83-c1357e9296fc"
        - name: Share_Path
          value: "/v2link"
